version: "3.8"

services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - marketing_network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - marketing_network

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - marketing_network

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - marketing_network

networks:
  marketing_network:
    driver: bridge
